export { default as GeneralTable } from './generalTable/GeneralTable'
export { default as Pagination } from './pagination/Pagination'
export { default as TableCell } from './tableCell/TableCell'
export { default as TableHead } from './tableHead/TableHead'
export { default as TableRow } from './tableRow/TableRow'
